export { Adolescente } from '../partes/adolescente'
export { Admterc } from '../partes/admterc'
export { Assista } from '../partes/assista'
export { AssMP } from '../partes/ass-mp'
export { Autoridade } from '../partes/autoridade'
export { Beneficiario } from '../partes/beneficiario'
export { ChamadoAoProcesso } from '../partes/chamado-ao-processo'
export { Comunicado } from '../partes/comunicado'
export { Comunicante } from '../partes/comunicante'
export { Corrigente } from '../partes/corrigente'
export { Corrigido } from '../partes/corrigido'
export { CriancaAdolescente } from '../partes/crianca-adolescente'
export { DeCujus } from '../partes/de-cujus'
export { Dilig } from '../partes/dilig'
export { EntidadeRelacionada } from '../partes/entidade-relacionada'
export { EntrePartes } from '../partes/entre-partes'
export { Falecido } from '../partes/falecido'
export { Habilitado } from '../partes/habilitado'
export { Habilitante } from '../partes/habilitante'
export { Informante } from '../partes/informante'
export { Infte } from '../partes/infte'
export { Interessado } from '../partes/interessado'
export { Marca } from '../partes/marca'
export { Perito } from '../partes/perito'
export { Procurador } from '../partes/procurador'
export { Representante } from '../partes/representante'
export { Inventariante } from '../partes/inventariante'
export { TerceiraPessoa } from '../partes/terceira-pessoa'
export { Terceiro } from '../partes/terceiro'
export { TerceiroInteressado } from '../partes/terceiro-interessado'
export { Terintcer } from '../partes/terintcer'
export { Terintinc } from '../partes/terintinc'
export { Testemunha } from '../partes/testemunha'

import { Adolescente } from '../partes/adolescente'
import { Admterc } from '../partes/admterc'
import { Assista } from '../partes/assista'
import { AssMP } from '../partes/ass-mp'
import { Autoridade } from '../partes/autoridade'
import { Beneficiario } from '../partes/beneficiario'
import { ChamadoAoProcesso } from '../partes/chamado-ao-processo'
import { Comunicado } from '../partes/comunicado'
import { Comunicante } from '../partes/comunicante'
import { Corrigente } from '../partes/corrigente'
import { Corrigido } from '../partes/corrigido'
import { CriancaAdolescente } from '../partes/crianca-adolescente'
import { DeCujus } from '../partes/de-cujus'
import { Dilig } from '../partes/dilig'
import { EntidadeRelacionada } from '../partes/entidade-relacionada'
import { EntrePartes } from '../partes/entre-partes'
import { Falecido } from '../partes/falecido'
import { Habilitado } from '../partes/habilitado'
import { Habilitante } from '../partes/habilitante'
import { Informante } from '../partes/informante'
import { Infte } from '../partes/infte'
import { Interessado } from '../partes/interessado'
import { Marca } from '../partes/marca'
import { Perito } from '../partes/perito'
import { Procurador } from '../partes/procurador'
import { Representante } from '../partes/representante'
import { Inventariante } from '../partes/inventariante'
import { TerceiraPessoa } from '../partes/terceira-pessoa'
import { Terceiro } from '../partes/terceiro'
import { TerceiroInteressado } from '../partes/terceiro-interessado'
import { Terintcer } from '../partes/terintcer'
import { Terintinc } from '../partes/terintinc'
import { Testemunha } from '../partes/testemunha'
import { Polo } from '.'

export type TypeTerceiro = Adolescente | Admterc | Assista | AssMP | Autoridade | Beneficiario | ChamadoAoProcesso | Comunicado | Comunicante | Corrigente | Corrigido | CriancaAdolescente | DeCujus | Dilig | EntidadeRelacionada | EntrePartes | Falecido | Habilitado | Habilitante | Informante | Infte | Interessado | Marca | Perito | Procurador | Representante | Inventariante | TerceiraPessoa | Terceiro | TerceiroInteressado | Terintcer | Terintinc | Testemunha

export interface DictTerceiro { [name: string]: TypeTerceiro }
export const ObjectTerceiro: DictTerceiro = Object.assign({}, Adolescente, Admterc, Assista, AssMP, Autoridade, Beneficiario, ChamadoAoProcesso, Comunicado, Comunicante, Corrigente, Corrigido, CriancaAdolescente, DeCujus, Dilig, EntidadeRelacionada, EntrePartes, Falecido, Habilitado, Habilitante, Informante, Infte, Interessado, Marca, Perito, Procurador, Representante, Inventariante, TerceiraPessoa, Terceiro, TerceiroInteressado, Terintcer, Terintinc, Testemunha)
Object.freeze(ObjectTerceiro)

export default Polo.Terceiro
